### ISSUE TITLE
[Bug][Projucer]: "Hardened Runtime" option in the Projucer does not set option in Xcode

### ISSUE THREAD

**Issue by mmomentum** [juce-framework/JUCE#1055]
### Detailed steps on how to reproduce the bug

I was recently having problems with getting my builds running via use of a build script in tandem with Xcode projects generated by the Projucer, the main issue was notarization, and it was failing because even though I had set the "Hardened Runtime" option inside of the Projucer, neither the debug or release schemes were actually having their hardened runtime options set inside of Xcode itself.

No idea if this is a new bug caused by some sort of update, or if maybe I missed some internal requirements for the option to be set correctly.

### What is the expected behaviour?

When "Use Hardened Runtime" is set inside of the Xcode exporter, it should set it inside of the Xcode project options.

### Operating systems

macOS

### What versions of the operating systems?

Montery 12.3.1

### Architectures

x86_64

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
What version of Xcode are you using? What version of JUCE are you using?

On Montery 12.3 (ARM) if I open the DemoRunner project in Projucer, toggle hardened runtime on, resave the project, then open the DemoRunner project in Xcode 13.3, I can see that hardened runtime has been set in the 'Signing and Capabilities' page. I can also see that we have the corresponding settings enabled in the Xcode .pbxproj file.

What happens if you follow the same procedure?

**Comment by mmomentum** [comment]
I think I may have fixed the issue. I rebuilt my Projucer executable and the problem seems to be gone now... No idea what was causing that.
