### ISSUE TITLE
[Bug]: Enabling iOS mic permissions while app is running causes crash

### ISSUE THREAD

**Issue by izzyreal** [juce-framework/JUCE#1125]
### Detailed steps on how to reproduce the bug

1. Create a JUCE audio application for iPadOS and enable microphone permissions and background audio for the project.
2. Run the application and when asked allow microphone input.
3. Close the app.
4. In iOS Settings > Privacy disable mic permissions for the app.
5. Start the app.
6. Enable mic permissions in Settings.

Then I get
```
Message from debugger: Terminated due to signal 9
Program ended with exit code: 9
```

### What is the expected behaviour?

Don't crash, but allow microphone input mid-lifetime.

### Operating systems

iPadOS 15.7

### What versions of the operating systems?

15.7

### Architectures

ARM, 64-bit

### Plug-in formats (if applicable)

Standalone

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by szarvas** [comment]
I think this might be by design on iOS.

The simplest iOS application I could create also received a kill signal from the system when changing the permissions in the described way. It would probably be fairer to call this a forced restart by the system, as opposed to a crash.

The top answer on this SO page also suggests that this is the general by-design behaviour on iOS.
https://stackoverflow.com/questions/62185187/ios-app-restarts-after-changing-revoked-privacy-settings

If you have information that this behaviour can be changed, please share it, and we'll take another look.
