### ISSUE TITLE
[Bug]: UnitTests fail on x86-32

### ISSUE THREAD

**Issue by umlaeute** [juce-framework/JUCE#1466]
### Detailed steps on how to reproduce the bug

- setup an i386 (x86, x86-32) machine
- build the UnitTestRunner
   ```sh
   make -C extras/UnitTestRunner/Builds/LinuxMakefile
   ```
- run the UnitTestRunner
   ```sh
   extras/UnitTestRunner/Builds/LinuxMakefile/build/UnitTestRunner
   ```

- notice that many tests fail

### What is the expected behaviour?

I expect JUCE to work i386 (aka `x86` or `x86-32`)

If this architecture is not supported (like powerpc #1464, and presumably s390/x), it would be great if you could specify the actually supported architectures.

### Operating systems

Linux

### What versions of the operating systems?

Debian/sid

### Architectures

32-bit

### Stacktrace

```shell
Time / Time: 1 test failure
approximatelyEqual<long double> / Tolerances scale with the values being compared: 1 test failure
OSCTimeTag class / Conversion to/from JUCE Time: 2 test failures
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Thank you for reporting.

We've changed a few of the tests so that they're not triggered on i386 systems, but having worked through a few other issues we have also decided that i386 Linux will not be an officially supported JUCE platform.

We have now listed the officially supported architectures in the README: https://github.com/juce-framework/JUCE/blob/develop/README.md#deployment-targets (and thank for for that suggestion too!).

**Comment by umlaeute** [comment]
Thanks a lot for the link to the list of officially supported architectures.
As an idea, you probably want to update your bug reporting template to just includes the systems (os/CPU combinations) that are supported (with a callback field "unsupported system").

Anyhow, I wonder what the page means with "Linux/armv7 should work but are not regularly tested)".
If I do encounter a build error for this platform, should I report it or not?

**Comment by tpoole** [comment]
I've updated the issue template too (but it'll take a while for that commit work through all of our CI).

If you do encounter problems with armv7 or similar please do report the bugs. "not regularly tested" was meant to imply that we would rely upon the JUCE community to let us know of any problems, rather than us continuously testing those platforms like we do with the others.
