### ISSUE TITLE
UI Elements Are Not Accessible with Screen Readers

### ISSUE THREAD

**Issue by chigkim** [juce-framework/JUCE#289]
Juce UI elements are not accessible with screen readers on Mac.
Steps to produce
1. build and run "examples/demo/MacOSX/JuceDemo.xcodeproj"
2. Wait for the window to display
3. Press command+f5 to turn on VoiceOver, the built-in screen reader for MacOS.
4. Try to navigate the window using VoiceOver cursor with control+option+arrows
VoiceOver cannot recognize any of the UI elements.
Is that possible to make Juce UI elements to adopt accessibility API?
https://developer.apple.com/library/content/documentation/Accessibility/Conceptual/AccessibilityMacOSX/
https://developer.apple.com/videos/play/wwdc2016/407/
This would allow developers to make their audio/instruments plugins accessible for screen reader users.
Thank you for your consideration!

**Comment by sseyod** [comment]
I agree with this - it is one primary reason why I still use native UIs for both iOS and macOS development, rather than Juce.

**Comment by Luke-Robinett** [comment]
Any update on this? I'd like to be able to load cartridges and programs in Dexed for Windows. Even if I could get the coordinates in pixels of where controls for opening carts and programs is on the plugin's UI, I could use a script to send the mouse cursor to that location and generate a click. This assumes it opens a typical Windows File Open dialog?
Otherwise, is there a way to load carts/programs some other way? MIDI program changes/CCs? I'm open minded here, but there's got to be some non-visual way to achieve this. Thanks.

**Comment by chigkim** [comment]
Yes, check out: https://forum.juce.com/t/juce-accessibility-on-develop/45142
