### ISSUE TITLE
iOS: SystemClipboard::getTextFromClipboard() crash potential when clipboard data isn't text

### ISSUE THREAD

**Issue by essej** [juce-framework/JUCE#956]
The current iOS implementation of  SystemClipboard::getTextFromClipboard() in `juce_gui_basics/native/juce_ios_Windowing.mm` blindly casts the results of valueForPasteboardType to string, when it is not guaranteed to be so. I have experienced crashes because of this on the occasions when it isn't.

The following re-implementation resolves the issue for me. 

```
String SystemClipboard::getTextFromClipboard()
{
    id value = [[UIPasteboard generalPasteboard] valueForPasteboardType: @"public.text"];
    if ([value isKindOfClass:[NSString class]]) {
        return nsStringToJuce (value);
    }
    return {};
}
```

**Comment by ed95** [comment]
Thanks for reporting. I was able to reproduce this and have pushed a slightly simpler fix in https://github.com/juce-framework/JUCE/commit/f2b9ab15d8724616f515136e7ffa660673d1286d. We can query the `string` property of the `UIPasteboard` instance which contains the first `NSString*` in the clipboard, or an empty `NSString*` otherwise, so we can safely pass it to `nsStringToJuce()`.
