### ISSUE TITLE
Keyboard focus still possible on hidden components

### ISSUE THREAD

**Issue by codecat** [juce-framework/JUCE#983]
When I have some button components set to be hidden using `setVisible(false)`, they can still be focused using the tab key, followed by pressing enter which will trigger the button.

Perhaps `Component::getWantsKeyboardFocus` should return false if the component is not visible, or `KeyboardFocusTraverserHelpers::isKeyboardFocusable` should return false instead.

**Comment by reuk** [comment]
I just tried out the following very tiny app (I replaced the MainComponent of the GuiApp CMake example with the following):

```cpp
class MainComponent  : public juce::Component
{
public:
    MainComponent()
    {
        setSize (600, 400);

        [this] (auto&&... arg) { (addAndMakeVisible (arg), ...); } (a, b, c);

        c.setVisible (false);
        c.setClickingTogglesState (true);
        c.onClick = [this] { repaint(); };
    }

private:
    template <typename... T>
    static juce::Array<juce::FlexItem> makeFlexItems (T&&... args)
    {
        return { juce::FlexItem (args).withFlex (1.0f).withMargin (20.0f)... };
    }

    void paint (juce::Graphics& g) override
    {
        g.fillAll (c.getToggleState() ? juce::Colours::cyan : juce::Colours::magenta);
    }

    void resized() override
    {
        juce::FlexBox fb;
        fb.items = makeFlexItems (a, b, c);
        fb.performLayout (getLocalBounds());
    }

    juce::TextButton a { "a" }, b { "b" }, c { "c" };

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainComponent)
};
```

If I click button 'a', then it gains keyboard focus. I can test this by hitting 'return', and verifying that the button is highlighted. When I press 'tab', keyboard focus moves to 'b'. When I press 'tab' again, keyboard focus loops back to 'a', bypassing the invisible button 'c'.

The issue doesn't seem to be present in the latest version of JUCE, so please make sure you're up-to-date. If the issue is still present after updating, please can you provide more details about the steps you're following to trigger the problem, and ideally provide some trimmed-down example code?

**Comment by codecat** [comment]
My apologies, you were right, this is indeed not a bug. This ended up being a bug in my UI design code, where `setVisible(false)` was never actually called and the "hidden" controls were actually just set to have a width and height of 0 due to having an invalid layout.

Thanks for looking into this!
