### ISSUE TITLE
Better practice with pthread on Linux: use `-pthread`

### ISSUE THREAD

**Issue by r-value** [juce-framework/JUCE#995]
Code reference: https://github.com/juce-framework/JUCE/blob/9055820a30770479e30994c9a91029474cf60f7d/modules/juce_core/juce_core.h#L45

According to gcc doc, `-pthread` flag will link the program against libraries like libatomic on demand and define a series of preprocessor macros, which is the expected usage of pthread. Using `pthread` in `linuxLibs` generates `-lpthread` flag in CFLAGS and LDFLAGS, which causes absense of these libraries, thus failing to build on architectures which needs soft atomic operation implementation.

Recommended change:
```patch
-  linuxLibs:          rt dl pthread
+  linuxLibs:          rt dl -pthread
```

Reference:
[GCC doc about concurrency](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_concurrency.html) indicates that `-pthread` should be used when building GNU/Linux targets.
> On several targets (including GNU/Linux, Solaris and various BSDs) -pthread is honored. Some other ports use other switches

[GCC doc about preprocessor flags](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options)

[Stack Overflow: Difference between -pthread and -lpthread](https://stackoverflow.com/questions/23250863/difference-between-pthread-and-lpthread-while-compiling)

**Comment by r-value** [comment]
In my case on RISC-V machines, `gcc -dumpspecs` includes `%{pthread:--push-state --as-needed -latomic --pop-state}`. `libpthread` **requires** `libatomic` to function correctly in RISC-V architecture. Your verification shows that although `libatomic` is needed to use `std::atomic` on ARM, but there is no dependency between `libpthread` and `libatomic` so that you will need to link that separately. It's consistent with requirements from user who will need to link `atomic` separately. This change solves the problem for both side: `pthread` on RISC-V architecture will function correctly, and `atomic` can be linked separately on other architectures like ARM.

Or in other words, `-pthread` **guarantees** that pthread will work correctly with all required things linked/defined. It's a better practice across all platforms (This assertion is consistent with documents from both `gcc` and `clang`).

**Comment by r-value** [comment]
@reuk 
Hi there, any ideas?

**Comment by reuk** [comment]
I'm still considering this change. The documentation for the `linuxLibs` field says that it is "A list of static or dynamic libs that should be linked in a linux build (these are passed to the linker via the -l flag)". It isn't a list of compiler flags, so I'm fairly sure that passing "-pthread" here (i.e. a compiler flag rather than the name of a library) is the wrong approach, unless we update the definition of `linuxLibs`, and update the Projucer/CMake to process this field appropriately.

At the moment, special-casing to link extra libraries (like the web browser, curl, and atomic libraries) happens in the build system rather than being derived directly from the module headers. This is probably the approach I'd take here too, rather than adding compiler flags to the module headers.

JUCE does not officially support the RISC-V architecture at the moment, and the current solution seems to work on all the platforms that we do support. I'll revisit this topic if we add support for more architectures in the future.

**Comment by tpoole** [comment]
When we're at the point of adopting the riscv64 architecture we'll run straight into this issue as it'll stop builds in our CI pipeline, so there's no risk of it being forgotten.
